version: '3.1'
services:
  jenkins:
    container_name: jenkins
    image: 1c4r0/jenkins-with-docker:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "./jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
